//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace med_webb_CapaDato.Modelado
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVentaPlatillo
    {
        public int Id { get; set; }
        public Nullable<int> VentaId { get; set; }
        public Nullable<int> PlatilloId { get; set; }
        public int Cantidad { get; set; }
        public decimal Total { get; set; }
    
        public virtual Platillo Platillo { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
